// <auto-generated />
using System;
using BellenodeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BellenodeApi.Migrations
{
    [DbContext(typeof(BellenodeDbContext))]
    [Migration("20260419000000_AddAuth")]
    partial class AddAuth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BellenodeApi.Models.CaisseMapping", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CodeCaisse").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<string>("CodeUnite").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("Quantite").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("CodeCaisse").IsUnique();
                b.ToTable("CaisseMappings");
            });

            modelBuilder.Entity("BellenodeApi.Models.InventoryItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Code").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<int>("RestaurantId").HasColumnType("int");
                b.Property<bool>("IsReferenced").HasColumnType("bit");
                b.Property<int>("Quantite").HasColumnType("int");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Code", "RestaurantId").IsUnique();
                b.ToTable("Inventory");
            });

            modelBuilder.Entity("BellenodeApi.Models.Product", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CodeSaq").HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<string>("CodeUpc").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Nom").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<decimal?>("Prix").HasColumnType("decimal(10,2)");
                b.Property<int?>("UnitesParCaisse").HasColumnType("int");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("CodeUpc").IsUnique();
                b.ToTable("Products");
            });

            modelBuilder.Entity("BellenodeApi.Models.Restaurant", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Nom").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Restaurants");
            });

            modelBuilder.Entity("BellenodeApi.Models.RestaurantObjectif", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CodeUpc").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<int>("ObjectifQty").HasColumnType("int");
                b.Property<int>("RestaurantId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("RestaurantId", "CodeUpc").IsUnique();
                b.ToTable("RestaurantObjectifs");
            });

            modelBuilder.Entity("BellenodeApi.Models.ScanBatch", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("LignesOps").HasColumnType("int");
                b.Property<string>("Note").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("ProduitsTouches").HasColumnType("int");
                b.Property<int>("RestaurantId").HasColumnType("int");
                b.Property<int>("TotalAjouts").HasColumnType("int");
                b.Property<int>("TotalRetraits").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("ScanBatches");
            });

            modelBuilder.Entity("BellenodeApi.Models.ScanOperation", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Code").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<bool>("IsReferenced").HasColumnType("bit");
                b.Property<int>("Mode").HasColumnType("int");
                b.Property<int>("QtyApres").HasColumnType("int");
                b.Property<int>("QtyAvant").HasColumnType("int");
                b.Property<int>("Quantite").HasColumnType("int");
                b.Property<int>("ScanBatchId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("ScanBatchId");
                b.ToTable("ScanOperations");
            });

            modelBuilder.Entity("BellenodeApi.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Nom").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("Role").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("BellenodeApi.Models.UserRestaurantAccess", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("RestaurantId").HasColumnType("int");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UserId", "RestaurantId").IsUnique();
                b.ToTable("UserRestaurantAccesses");
            });

            modelBuilder.Entity("BellenodeApi.Models.ScanOperation", b =>
            {
                b.HasOne("BellenodeApi.Models.ScanBatch", "ScanBatch")
                    .WithMany("Operations")
                    .HasForeignKey("ScanBatchId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("ScanBatch");
            });

            modelBuilder.Entity("BellenodeApi.Models.UserRestaurantAccess", b =>
            {
                b.HasOne("BellenodeApi.Models.User", "User")
                    .WithMany("RestaurantAccesses")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("BellenodeApi.Models.Restaurant", "Restaurant")
                    .WithMany("UserAccesses")
                    .HasForeignKey("RestaurantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Restaurant");
                b.Navigation("User");
            });

            modelBuilder.Entity("BellenodeApi.Models.ScanBatch", b => b.Navigation("Operations"));
            modelBuilder.Entity("BellenodeApi.Models.User", b => b.Navigation("RestaurantAccesses"));
            modelBuilder.Entity("BellenodeApi.Models.Restaurant", b => b.Navigation("UserAccesses"));
#pragma warning restore 612, 618
        }
    }
}
