// <auto-generated />
using BellenodeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BellenodeApi.Migrations
{
    [DbContext(typeof(BellenodeDbContext))]
    [Migration("20260420000000_AddRestaurantRoles")]
    partial class AddRestaurantRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
